/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openda_costa_CtaInitialize */

#ifndef _Included_org_openda_costa_CtaInitialize
#define _Included_org_openda_costa_CtaInitialize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openda_costa_CtaInitialize
 * Method:    ctaInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaInitialize_ctaInit
  (JNIEnv *, jclass);

/*
 * Class:     org_openda_costa_CtaInitialize
 * Method:    setRandomSeed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaInitialize_setRandomSeed
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
