      FUNCTION CSEDRESB(DENBULK,WRSPO,VDRO,VDR,VDRC,IOPT)  
C  
C CHANGE RECORD  
C  
C  
C **  CALCULATES BULK EROSION RATE OF COHESIVE  
C **  SEDIMENT AS A FUNCTION OF BED BULK DENSITY AND OTHER VARIABLES  
C **  CURRENT OPTIONS SHOULD NOT BE USED  
C **  IOPT=1  BASED ON  
C **  
C **  HWANG, K. N., AND A. J. MEHTA, 1989: FINE SEDIMENT ERODIBILITY  
C **  IN LAKE OKEECHOBEE FLORIDA. COASTAL AND OCEANOGRAPHIC ENGINEERING  
C **  DEPARTMENT, UNIVERSITY OF FLORIDA, GAINESVILLE, FL32661  
C **  IOPT=2  BASED ON J. M. HAMRICK'S MODIFICATION OF  
C **  
C **  SANFORD, L.P., AND J. P. Y. MAA, 2001: A UNIFIED EROSION FORMULATI  
C **  FOR FINE SEDIMENT, MARINE GEOLOGY, 179, 9-23.  
C  
      IF(IOPT.GE.1)CSEDRESB=0.0  
C  
C        DENBULK=0.001*DENBULK  
C          CSEDRESB=0.62  
C        ELSE  
C          TMP=0.198/(DENBULK-1.0023)  
C          CSEDRESB=6.4E-4*(10.**TMP)  
C  
      RETURN  
      END  

