      FUNCTION CSEDTAUB(DENBULK,TDUM,V1,V2,V3,IOPT)  
C  
C CHANGE RECORD  
C
C  
C **  CALCULATES CRITIAL STRESS FOR BULK OR MASS EROSION OF COHESIVE  
C **  SEDIMENT AS A FUNCTION OF BED BULK DENSITY  
C **  IOPT=1  BASED ON  
C **  
C **  HWANG, K. N., AND A. J. MEHTA, 1989: FINE SEDIMENT DRODIBILITY  
C **  IN LAKE OKEECHOBEE FLORIDA. COASTAL AND OCEANOGRAPHIC ENGINEERING  
C **  DEPARTMENT, UNIVERSITY OF FLORIDA, GAINESVILLE, FL32661  
C **  IOPT=2  BASED ON  
C **  
C **  HWANG, K. N., AND A. J. MEHTA, 1989: FINE SEDIMENT DRODIBILITY  
C **  IN LAKE OKEECHOBEE FLORIDA. COASTAL AND OCEANOGRAPHIC ENGINEERING  
C **  DEPARTMENT, UNIVERSITY OF FLORIDA, GAINESVILLE, FL32661  
C  
      IF(IOPT.EQ.1)THEN  
        BULKDEN=0.001*DENBULK  ! *** PMC Changed to prevent 
        IF(BULKDEN.LE.1.013)THEN  
          CSEDTAUB=0.0  
        ELSE  
          CSEDTAUB=0.001*(9.808*BULKDEN-9.934)  
        ENDIF  
      ELSEIF(IOPT.EQ.2)THEN  
        BULKDEN=0.001*DENBULK  ! *** PMC Changed to prevent 
        IF(BULKDEN.LE.1.013)THEN  
          CSEDTAUB=0.0  
        ELSE  
          CSEDTAUB=0.001*(9.808*BULKDEN-9.934)  
        ENDIF  
      ELSE
        STOP 'CSEDTAUB: BAD SEDIMENT CRITICAL STRESS OPTION! STOPPING!'
      ENDIF  
C
      RETURN  
      END  

