      SUBROUTINE DEPPLT  
C  
C **  SUBROUTINE DEPPLT WRITES A FILE TO CONTOUR PLOT DEPTH  
C CHANGE RECORD  
C  
      USE GLOBAL  

      CHARACTER*80 TITLE  

      OPEN(1,FILE='BELVCON.OUT',STATUS='UNKNOWN')  
      CLOSE(1,STATUS='DELETE')  
      OPEN(1,FILE='BELVCON.OUT',STATUS='UNKNOWN')  
      TITLE='BOTTOM ELEVATION CONTOURS'  
      NTIME=1  
      LINES=LA-1  
      LEVELS=1  
      DBS=0.  
      WRITE (1,99) TITLE  
      WRITE (1,100)LINES,LEVELS  
      WRITE (1,250)DBS  
      WRITE (1,100)NTIME  
      DO L=2,LA  
        WRITE(1,200)IL(L),JL(L),DLON(L),DLAT(L),BELV(L)  
      ENDDO  
      CLOSE(1)  
   99 FORMAT(A80)  
  100 FORMAT(I10)  
  101 FORMAT(2I10)  
  200 FORMAT(2I5,1X,2D12.6,F12.6)  
  250 FORMAT(12F10.6)  
      RETURN  
      END  

