      FUNCTION FHYDCN(VOID,BMECH4,BMECH5,BMECH6,IBMECHK)  
C  
C CHANGE RECORD  
C  ADDED STANDARD EXPONENTIAL FORM CONSTITUTIVE RELATIONSHIP  
C  
C  
C **  FHYDCN IS HYDRAULIC CONDUCTIVITY DIVIDED BY 1+VOID RATIO  
C  
      IF(BMECH4.GT.0.0)THEN  
        TMP=(VOID-BMECH5)/BMECH6  
        IF(IBMECHK.EQ.0) THEN  
          FHYDCN=BMECH4*EXP(TMP)/(1.+VOID)  
        ELSE  
          FHYDCN=BMECH4*EXP(TMP)  
        END IF  
      ELSE  
        FHYDCNLOG=0.00816448*(VOID**3)-0.232453*(VOID**2)+2.5759*VOID  
     &      -28.581  
        FHYDCN=EXP(FHYDCNLOG)  
      END IF  
      RETURN  
      END  

