      SUBROUTINE OUTPUT2  
C  
C CHANGE RECORD  
C  
      USE GLOBAL  
C  
C **  OUTPUT RESULTS OF RELAXATION SOLUTION  
C  
      WRITE (7,40) RP  
   40 FORMAT (1H1,' RESULTS OF RELAX SOLUTION - RP=',F5.2,//)  
      WRITE (7,41)  
   41 FORMAT (' GLOBAL SQUARED ERROR',//)  
      WRITE(7,43)ERRMAX,ERRMIN  
   43 FORMAT('ERRMAX =',3X,E12.4,5X,'ERRMIN =',3X,E12.4)  
   20 FORMAT (1X,I5,3X,10E12.4)  
      WRITE(7,40)RP  
      WRITE (7,42)  
   42 FORMAT (' ITERATIONS TO CONVERGENCE',//)  
      WRITE(7,44)ITRMAX,ITRMIN  
   44 FORMAT('ITRMAX =',I5,5X,'ITRMIN =',I5)  
   21 FORMAT (1X,I5,5X,10I10)  
   30 FORMAT (10E12.4)  
C  
C **  OUTPUT HARMONIC ANALYSIS  
C  
      DO L=2,LA  
        PAM(L)=(AMCP(L)*AMCP(L)+AMSP(L)*AMSP(L))**.5  
        IF(AMSP(L).EQ.0.0.AND.AMCP(L).EQ.0.0)THEN  
          PPH(L)=999999.  
        ELSE  
          PPH(L)=ATAN2(AMSP(L),AMCP(L))  
        ENDIF  
      ENDDO  
      DO L=2,LA  
        PAM(L)=PAM(L)*GI  
      ENDDO  
      WRITE (7,55)  
      CALL PPLOT (1)  
   55 FORMAT (1H1,'TIDAL SURFACE DISPLACEMENT AMPLITUDE IN METERS',//)  
      DO L=2,LA  
        PAM(L)=0.5*TIDALP*PPH(L)/PI  
      ENDDO  
      WRITE(7,588)  
      CALL PPLOT (1)  
  588 FORMAT (1H1,'TIDAL SURFACE DISPLACEMENT PHASE IN SEC',//)  
C  
C **  PRINTED OUTPUT OF P,U,AND V AMPLITUDES  
C  
   72 FORMAT(3I5,4(3X,E12.4))  
C  
C **  OUTPUT VECTOR POTENTIAL TRANSPORT VELOCITY  
C  
 1458 FORMAT(1H1,' X VECTOR POTENTIAL TRANSPORT VEL, M/S, LAYER',I5,//)  
 1459 FORMAT(1H1,' Y VECTOR POTENTIAL TRANSPORT VEL, M/S, LAYER',I5,//)  
  100 CONTINUE  
      RETURN  
      END  

