! Advanced EFDC Hydraulic structure ! GEOSR. 2011. 12. JGCHO
!
      SUBROUTINE SCANGATECTL
      USE GLOBAL

      WRITE(*,'(A)')'SCANNING INPUT FILE: GATECTL.INP'

      OPEN(1,FILE='GATECTL.INP',STATUS='UNKNOWN')  
      ! *** FINE MAXIMUM NUMBER OF GATE TYPES
      CALL SEEK('GC1')
      READ(1,*,IOSTAT=ISO) NGTYPES
	IF(ISO.GT.0)GOTO 20  
	NGTYPEM=MAX(1,NGTYPES)        ! GATE TYPE NO.
      ! *** FIND MAXIMUM NUMBER OF TABLE DATA POINTS  
      NICMPM=1
      NOCMPM=1
      CALL SEEK('GC6')
      DO L=1,NGTYPEM
        READ(1,*,IOSTAT=ISO) NICMPTMP,NOCMPTMP
        IF(ISO.GT.0)GOTO 20  
        NICMPM=MAX(NICMPM,NICMPTMP) ! UPSTREAM ELEV. COMPARE CELL NO.
        NOCMPM=MAX(NOCMPM,NOCMPTMP) ! DOWNSTREAM ELEV. COMPARE CELL NO.
      ENDDO
      CLOSE(1)
	
! { GEOSR 2014.11.12 UNG Warning message writing
      OPEN(1,FILE='GateWarning.LOG',STATUS='UNKNOWN')  		! GEOSR UNG 2014.11.12 Warning message writing
      CLOSE(1,STATUS='DELETE')											  		! GEOSR UNG 2014.11.12 Warning message writing
	OPEN(713,FILE='GateWarning.LOG',STATUS='UNKNOWN')		! GEOSR UNG 2014.11.12 Warning message writing
	WRITE(713,'(A)')'TIME   N    NCTL    IQCTLU   JQCTLU    QSUM   CellVOL'
! } GEOSR 2014.11.12 UNG Warning message writing
      
      RETURN

C  10 FORMAT(A80)   
   20 WRITE(*,30)'GATECTL.INP'
      WRITE(8,30)'GATECTL.INP'
   30 FORMAT(' READ ERROR IN FILE: GATECTL.INP ')
      STOP

      END
