      SUBROUTINE SKIPCOMM(IUNIT, CC)  
C  
C CHANGE RECORD  
C SKIPS OVER COMMENT LINES IN INPUT FILES  
C  
      CHARACTER CC*1, LINE*120
  100 READ(IUNIT, 8, END=999) LINE  
      WRITE(2,9)LINE
      IF(LINE(1:1) .EQ. CC) GOTO 100  
      IF(LINE(1:1) .EQ. 'C') GOTO 100  
      IF(LINE(1:1) .EQ. 'c') GOTO 100  
      BACKSPACE(IUNIT)  
  999 RETURN  
    8 FORMAT(A120)
    9 FORMAT(1X,A120)
      END  

