      SUBROUTINE TIMELOG(N,TIMEDAY)  
      CHARACTER*8 MRMDATE,MRMTIME*10  
C  
C WRITE OUT MODEL TIME STEP AND SUN/PC SYSTEM CLOCK TIME TO TIME.LOG FIL  
C  
      ! *** WRITE OUT MODEL TIME STEP AND SYSTEM CLOCK TIME TO TIME.LOG  
      CALL DATE_AND_TIME(MRMDATE,MRMTIME)  
      WRITE(9,100)N,TIMEDAY,MRMDATE,MRMTIME  
  100 FORMAT(' ','N =',I10,5X,'TIMEDAY = ',F12.4,5X,'DATE = ',A8,  
     &    5X,'TIME = ',A10)  
      RETURN  
      END  
 
