      SUBROUTINE VARALLOC

      USE GLOBAL  
C  
      WRITE(*,'(A)')'ALLOCATING ARRAYS'  
C  
      CALL VARALLOC1
      CALL VARALLOC2
      CALL VARALLOC3
      CALL VARALLOC4
      CALL VARALLOC5
      CALL VARALLOC6
      CALL VARALLOC7
      CALL VARALLOC8
C
      RETURN  
      END  

