%YAML 1.1
---
# input for 1d reactive pollution model
#
# grid
x : [0.0, 60.0, 3600.0]
# stationary flow
u : [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
# cross sectional area
a : [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
# simulation timespan
refdate : '01 dec 1999'
#unit is always seconds
unit : 'seconds'
# sources mass/m^3/s
reaction_time: 1000.0 #oda:reaction_time
time: [0.0, 60.0, 15000.0] #oda:time_control
initial_values:
- id: 'c1'
  substance : 1
  file: input/concentration1.txt
- id: 'c2'
  substance : 2
  file: input/concentration2.txt
sources:
- id: 'c1_factory1'
  location : 5
  substance : 1
  file : forcings/c1_factory1.csv
  values : []
- id: 'c1_factory2'
  location : 30
  substance : 1
  file: forcings/c1_factory2.csv
  values : []
#output (index based and 0 based)
output_file : reactive_pollution_model.output
matlab_output_file : reactive_pollution_model_output.m
output:
  directory: output
  maps :
  - id: 'c1'
    times:  [0.0, 60.0, 15000.0]
    substance : 1
    file: maps/concentration1_{}.txt
  - id: 'c2'
    times:  [0.0, 60.0, 15000.0]
    substance : 2
    file: maps/concentration2_{}.txt
  restart :
  - id: 'c1'
    substance : 1
    file: restart/concentration1.txt
  - id: 'c2'
    substance : 2
    file: restart/concentration2.txt
  timeseries:
  - id: 'c1_locA'
    location: 10
    substance : 1
  - id: 'c1_locB'
    location: 20
    substance : 1
  - id: 'c1_locC'
    location: 40
    substance : 1
  - id: 'c2_locA'
    location: 10
    substance : 2
  - id: 'c2_locB'
    location: 20
    substance : 2
  - id: 'c2_locC'
    location: 40
    substance : 2
# boundaries
# only left and right at locations 0 and -1 allowed at the moment
boundaries:
- id: 'c1_left'
  location: 0
  substance : 1
  values:  [0.01]
- id: 'c1_right'
  location: -1
  substance : 1
  values:  [0.0]
- id: 'c2_left'
  location: 0
  substance : 2
  values:  [0.01]
- id: 'c2_right'
  location: -1
  substance : 2
  values:  [0.0]




