/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_costa_CtaTime */

#ifndef _Included_org_costa_CtaTime
#define _Included_org_costa_CtaTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_costa_CtaTime
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaTime_create
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    isStamp
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openda_costa_CtaTime_isStamp
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    getMJD
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaTime_getMJD
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    getUserTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaTime_getUserTime
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    setMJD
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaTime_setMJD
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_costa_CtaTime
 * Method:    setUserTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaTime_setUserTime
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_costa_CtaTime
 * Method:    isSpan
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openda_costa_CtaTime_isSpan
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    getStep
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openda_costa_CtaTime_getStep
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    getBeginMJD
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaTime_getBeginMJD
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    getEndMJD
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaTime_getEndMJD
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    getStepMJD
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaTime_getStepMJD
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    getBeginUserTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaTime_getBeginUserTime
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    getEndUserTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaTime_getEndUserTime
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    getUserStep
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaTime_getUserStep
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    setSpanMJD
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaTime_setSpanMJD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_costa_CtaTime
 * Method:    setUserSpan
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaTime_setUserSpan
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_costa_CtaTime
 * Method:    getStepCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openda_costa_CtaTime_getStepCount
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaTime
 * Method:    clone
 * Signature: ()Lorg/openda/interfaces/ITime;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaTime_clone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
