/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openda_costa_CtaModelState */

#ifndef _Included_org_openda_costa_CtaModelState
#define _Included_org_openda_costa_CtaModelState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openda_costa_CtaModelState
 * Method:    nativeSavePersistentState
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaModelState_nativeSavePersistentState
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
