/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openda_costa_CtaParallel */

#ifndef _Included_org_openda_costa_CtaParallel
#define _Included_org_openda_costa_CtaParallel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openda_costa_CtaParallel
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaParallel_nativeInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_openda_costa_CtaParallel
 * Method:    finalizeParallelEnvironment
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaParallel_finalizeParallelEnvironment
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
