/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openda_costa_CtaUtils */

#ifndef _Included_org_openda_costa_CtaUtils
#define _Included_org_openda_costa_CtaUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openda_costa_CtaUtils
 * Method:    print_memory
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaUtils_print_1memory
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
