/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openda_costa_CtaOpenDaModel */

#ifndef _Included_org_openda_costa_CtaOpenDaModel
#define _Included_org_openda_costa_CtaOpenDaModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    getCurrentTime
 * Signature: ()Lorg/openda/interfaces/ITime;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaOpenDaModel_getCurrentTime
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    getTimeHorizon
 * Signature: ()Lorg/openda/interfaces/ITime;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaOpenDaModel_getTimeHorizon
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    setAutomaticNoiseGeneration
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaOpenDaModel_setAutomaticNoiseGeneration
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaCreate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaAnnounceObservedValues
 * Signature: (Lorg/openda/interfaces/IObservationDescriptions;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaAnnounceObservedValues
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaAxpyOnParameters
 * Signature: (DLorg/openda/interfaces/IVector;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaAxpyOnParameters
  (JNIEnv *, jobject, jdouble, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaAxpyOnStateDomain
 * Signature: (DLorg/openda/interfaces/IVector;I)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaAxpyOnStateDomain
  (JNIEnv *, jobject, jdouble, jobject, jint);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaCompute
 * Signature: (Lorg/openda/interfaces/ITime;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaCompute
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaGetObservedValues
 * Signature: (Lorg/openda/interfaces/IObservationDescriptions;Lorg/openda/costa/CtaVector;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaGetObservedValues
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaGetState
 * Signature: ()Lorg/openda/interfaces/IVector;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaGetState
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaGetStateDomain
 * Signature: (I)Lorg/openda/interfaces/IVector;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaGetStateDomain
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaGetParameters
 * Signature: ()Lorg/openda/interfaces/IVector;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaGetParameters
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaGetStateScaling
 * Signature: ()Lorg/openda/interfaces/IVector;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaGetStateScaling
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaReleaseInternalState
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaReleaseInternalState
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaLoadPersistentState
 * Signature: (Ljava/lang/String;)Lorg/openda/interfaces/IModelState;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaLoadPersistentState
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaSaveInternalState
 * Signature: ()Lorg/openda/interfaces/IModelState;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaSaveInternalState
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaRestoreInternalState
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaRestoreInternalState
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaGetObservedLocalization
 * Signature: (Lorg/openda/interfaces/IObservationDescriptions;D)[I
 */
JNIEXPORT jintArray JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaGetObservedLocalization
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaGetObservedLocalizationDomain
 * Signature: (Lorg/openda/interfaces/IObservationDescriptions;DI)[I
 */
JNIEXPORT jintArray JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaGetObservedLocalizationDomain
  (JNIEnv *, jobject, jobject, jdouble, jint);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaSetParameters
 * Signature: (Lorg/openda/interfaces/IVector;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaSetParameters
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaGetNumDomains
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaGetNumDomains
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_openda_costa_CtaOpenDaModel
 * Method:    ctaGetObservationSelector
 * Signature: (Lorg/openda/interfaces/IObservationDescriptions;DI)[I
 */
JNIEXPORT jintArray JNICALL Java_org_openda_costa_CtaOpenDaModel_ctaGetObservationSelector
  (JNIEnv *, jobject, jobject, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
