/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openda_resultwriters_NetcdfResultWriterNative */

#ifndef _Included_org_openda_resultwriters_NetcdfResultWriterNative
#define _Included_org_openda_resultwriters_NetcdfResultWriterNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openda_resultwriters_NetcdfResultWriterNative
 * Method:    ctaNetcdfInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openda_resultwriters_NetcdfResultWriterNative_ctaNetcdfInit
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_openda_resultwriters_NetcdfResultWriterNative
 * Method:    ctaNetcdfClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_openda_resultwriters_NetcdfResultWriterNative_ctaNetcdfClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
