/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openda_costa_CtaArray */

#ifndef _Included_org_openda_costa_CtaArray
#define _Included_org_openda_costa_CtaArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openda_costa_CtaArray
 * Method:    create
 * Signature: ([D[I)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_create
  (JNIEnv *, jobject, jdoubleArray, jintArray);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getNumberOfDimensions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaArray_getNumberOfDimensions
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getDimensions
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_openda_costa_CtaArray_getDimensions
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaArray_length
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getValuesAsDoubles
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_openda_costa_CtaArray_getValuesAsDoubles__
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getValuesAsDoubles
 * Signature: (Z)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_openda_costa_CtaArray_getValuesAsDoubles__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getValuesAsDoubles
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_openda_costa_CtaArray_getValuesAsDoubles__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getValueAsDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaArray_getValueAsDouble__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getValueAsDouble
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_org_openda_costa_CtaArray_getValueAsDouble___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    setConstant
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_setConstant
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    setValuesAsDoubles
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_setValuesAsDoubles___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    setValuesAsDoubles
 * Signature: (II[D)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_setValuesAsDoubles__II_3D
  (JNIEnv *, jobject, jint, jint, jdoubleArray);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    setValueAsDouble
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_setValueAsDouble__ID
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    setValueAsDouble
 * Signature: ([ID)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_setValueAsDouble___3ID
  (JNIEnv *, jobject, jintArray, jdouble);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    axpyOnValues
 * Signature: (D[D)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_axpyOnValues
  (JNIEnv *, jobject, jdouble, jdoubleArray);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    multiplyValues
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_multiplyValues
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    reshape
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_reshape
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getSlice
 * Signature: (II)Lorg/openda/interfaces/IArray;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaArray_getSlice__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getSlice
 * Signature: (III)Lorg/openda/interfaces/IArray;
 */
JNIEXPORT jobject JNICALL Java_org_openda_costa_CtaArray_getSlice__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    getSliceAsDoubles
 * Signature: (III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_openda_costa_CtaArray_getSliceAsDoubles
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    setSlice
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_setSlice___3DII
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    setSliceBySlice
 * Signature: (Lorg/openda/interfaces/IArray;II)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_setSliceBySlice__Lorg_openda_interfaces_IArray_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    setSliceBySlice
 * Signature: (Lorg/openda/interfaces/IArray;III)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_setSliceBySlice__Lorg_openda_interfaces_IArray_2III
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    setSlice
 * Signature: ([DIII)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaArray_setSlice___3DIII
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint);

/*
 * Class:     org_openda_costa_CtaArray
 * Method:    valueIndex
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaArray_valueIndex
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
