/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openda_costa_CtaObject */

#ifndef _Included_org_openda_costa_CtaObject
#define _Included_org_openda_costa_CtaObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openda_costa_CtaObject
 * Method:    ctaFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaObject_ctaFree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
