subroutine model_init

  use global
  use mpi

  ! arguments
  !real, intent(out) :: time_period

  ! local
  CHARACTER(len=80) :: TITLE

  call model_init_1  ! opens output files

  ! **  CALL INPUT SUBROUTINE
  CALL VARINIT

  CALL INPUT(TITLE)

  CALL MPI_DECOMPOSITION

  call model_init_2

  ! **  READ RESTART CONDITIONS OR INITIALIZE SCALAR FIELDS  
  ! ISRESTI.EQ.10 READS AND OLD RESTART FILE GENERATED BY  
  ! PRE SEPTEMBER 8, 1992 VERSIONS OF EFDC.FOR  
  IF(ISRESTI.GE.1)THEN  
     IF(ISRESTI.EQ.1) CALL RESTIN1  
     IF(ISRESTI.EQ.2) CALL RESTIN2  
     IF(ISRESTI.EQ.10) CALL RESTIN10  
  ENDIF
  IF(ISRESTI.EQ.-1) CALL RESTIN1

  call model_init_3
  
end subroutine model_init

