/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openda_costa_CtaObservationDescriptions */

#ifndef _Included_org_openda_costa_CtaObservationDescriptions
#define _Included_org_openda_costa_CtaObservationDescriptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openda_costa_CtaObservationDescriptions
 * Method:    getPropertyKeys
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_openda_costa_CtaObservationDescriptions_getPropertyKeys
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaObservationDescriptions
 * Method:    ctaCreateSelection
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaObservationDescriptions_ctaCreateSelection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openda_costa_CtaObservationDescriptions
 * Method:    ctaCreateTimeSelection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaObservationDescriptions_ctaCreateTimeSelection
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openda_costa_CtaObservationDescriptions
 * Method:    getObservationCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaObservationDescriptions_getObservationCount
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaObservationDescriptions
 * Method:    getPropertyCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaObservationDescriptions_getPropertyCount
  (JNIEnv *, jobject);

/*
 * Class:     org_openda_costa_CtaObservationDescriptions
 * Method:    getStringProperties
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_openda_costa_CtaObservationDescriptions_getStringProperties
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openda_costa_CtaObservationDescriptions
 * Method:    ctaCreateNativeToJavaObserver
 * Signature: (Lorg/openda/interfaces/IObservationDescriptions;)I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaObservationDescriptions_ctaCreateNativeToJavaObserver
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_openda_costa_CtaObservationDescriptions
 * Method:    ctaGetValueProperties
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaObservationDescriptions_ctaGetValueProperties
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
