/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_costa_CtaRelationTable */

#ifndef _Included_org_costa_CtaRelationTable
#define _Included_org_costa_CtaRelationTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_costa_CtaRelationTable
 * Method:    ctaCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openda_costa_CtaRelationTable_ctaCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_costa_CtaRelationTable
 * Method:    SetTableCombine
 * Signature: (Lorg/openda/interfaces/IRelationTable;ZLorg/openda/interfaces/IRelationTable;Z)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaRelationTable_SetTableCombine
  (JNIEnv *, jobject, jobject, jboolean, jobject, jboolean);

/*
 * Class:     org_costa_CtaRelationTable
 * Method:    SetSelect
 * Signature: (Lorg/openda/interfaces/IVector;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaRelationTable_SetSelect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_costa_CtaRelationTable
 * Method:    apply
 * Signature: (Lorg/openda/interfaces/IVector;Lorg/openda/interfaces/IVector;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaRelationTable_apply
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_costa_CtaRelationTable
 * Method:    applyInv
 * Signature: (Lorg/openda/interfaces/IVector;Lorg/openda/interfaces/IVector;)V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaRelationTable_applyInv
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_costa_CtaRelationTable
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openda_costa_CtaRelationTable_free
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
