/*
COSTA: Problem solving environment for data assimilation
Copyright (C) 2005  Nils van Velzen

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

/**
\file  cta_flush.h
\brief Flush function for compatibility reasons with FORTRAN.
*/

#ifndef CTA_FLUSH_H
#define CTA_FLUSH_H

#include "cta_system.h"

/* Function Handle */
#ifdef __cplusplus
extern "C" {
#endif

/* functions */
/** \brief Flushes STDOUT and STDERR both for C as FORTRAN
 *
 *  \note Function is introduced because some FORTRAN compilers use
 *  different flushing than the C compiler. As a result the order of output
 *  generated by both languages is "random". This routine makes sure that
 *  all buffers have been flushed.
 *
 */
CTAEXPORT void CTA_Flush();
#ifdef __cplusplus
}
#endif
#endif

