name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup Java environment
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Update Ubuntu packages
        run: sudo apt-get update
      - name: Install Ubuntu packages
        run: sudo apt-get install jq gfortran mpi-default-dev libnetcdf-dev liblapack-dev
      - name: Build Native code
        run: ./install_native_travis.sh
      - name: Build Castor xml-parser code
        run: ./install_castor.sh
      - name: Run the Tests (from the old Travis script)
        run: ./travis_test.sh
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ant-test-reports
          path: opendaTestReports
        
      
